name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger on commits to the master branch
    tags:
      - 'v*'    # Trigger on tags starting with 'v' (e.g., v1.0.0)

jobs:
  build-net-core:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0  # Replace with your .NET Core version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build .NET Core solution
        run: dotnet build --configuration Release --no-restore

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-net-core  # Ensure this job runs after the .NET Core build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')  # Only log in if a tag is pushed
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract repository name
        id: extract-repo-name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $2}')
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}  # Push only if a tag is pushed

      - name: Push Docker image
        if: startsWith(github.ref, 'refs/tags/')  # Only push if a tag is pushed
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.ref_name }}  # Use the tag name (e.g., v1.0.0)
          push: true
